package Ventanas;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author José ÁNgel Trevilla
 */
public class AltaRegistro extends javax.swing.JFrame {

    Thread Hilo_registro;
    Thread Hilo_clean;

    // static String saldo;
    /**
     * Creates new form AltaRegistro
     */
    public AltaRegistro() {

        initComponents();
        setLocationRelativeTo(null);
        //Formulario.setBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED), "datos",  TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION));

    }//END METODO Cnstructor()

    public void RegistroEmpleados() {

        Hilo_registro = new Thread(new Runnable() {
            @Override
            public void run() {

                File archivo;
                archivo = new File("src\\registros\\empleados.txt");

                try {
                    if (!archivo.exists()) {

                        archivo.createNewFile();
                        FileWriter escribir = new FileWriter(archivo, true);
                        escribir.write(TXTNumE.getText() + "  ");
                        DecimalFormat df1 = new DecimalFormat("#.00");
                        String saldoI = TXTBalance.getText();
                        Double sd1 = Double.parseDouble(saldoI);
                        escribir.write(df1.format(sd1) + "\n");
                        escribir.close();
                        JOptionPane.showMessageDialog(null, "Se ha registrado correctamente");
                        Clean();
                    } else {
                        FileWriter escribir = new FileWriter(archivo, true);
                        escribir.write(TXTNumE.getText() + "  ");

                        DecimalFormat df = new DecimalFormat("#.00");
                        String saldoI = TXTBalance.getText();
                        Double sd = Double.parseDouble(saldoI);
                        escribir.write(df.format(sd) + "\n");

                        escribir.close();
                        JOptionPane.showMessageDialog(null, "Se ha registrado correctamente");
                        Clean();
                    }
                } catch (IOException ex) {
                    Logger.getLogger(AltaRegistro.class.getName()).log(Level.SEVERE, null, ex);
                }

            }//END Método run()
        });

        Hilo_registro.start();

    }//END METODO RegistroEmpleados()

    public void Clean() {

        Hilo_clean = new Thread(new Runnable() {
            @Override
            public void run() {
                TXTNumE.setText(null);
                TXTBalance.setText(null);

            }//NED METODO run()
        });
        Hilo_clean.start();
    }//END METODO Clean()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNLeer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JPanel();
        Sombra = new javax.swing.JPanel();
        Formulario = new javax.swing.JPanel();
        BarraTop = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTNumE = new javax.swing.JTextField();
        Balance = new javax.swing.JLabel();
        TXTBalance = new javax.swing.JTextField();
        BTNRegistrar = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        BTNLeer.setText("leer");
        BTNLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLeerActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(18, 22, 53));

        Sombra.setBackground(new java.awt.Color(11, 16, 42));

        Formulario.setBackground(new java.awt.Color(27, 33, 65));

        BarraTop.setBackground(new java.awt.Color(79, 217, 137));

        javax.swing.GroupLayout BarraTopLayout = new javax.swing.GroupLayout(BarraTop);
        BarraTop.setLayout(BarraTopLayout);
        BarraTopLayout.setHorizontalGroup(
            BarraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BarraTopLayout.setVerticalGroup(
            BarraTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        Titulo.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 204, 204));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Registro ");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Número empleado");

        TXTNumE.setBackground(new java.awt.Color(35, 41, 75));
        TXTNumE.setForeground(new java.awt.Color(153, 153, 153));
        TXTNumE.setBorder(null);

        Balance.setForeground(new java.awt.Color(204, 204, 204));
        Balance.setText("Balance");

        TXTBalance.setBackground(new java.awt.Color(35, 41, 75));
        TXTBalance.setForeground(new java.awt.Color(153, 153, 153));
        TXTBalance.setBorder(null);

        BTNRegistrar.setBackground(new java.awt.Color(234, 66, 137));
        BTNRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BTNRegistrar.setText("Registrar");
        BTNRegistrar.setBorder(null);
        BTNRegistrar.setBorderPainted(false);
        BTNRegistrar.setFocusPainted(false);
        BTNRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormularioLayout = new javax.swing.GroupLayout(Formulario);
        Formulario.setLayout(FormularioLayout);
        FormularioLayout.setHorizontalGroup(
            FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BarraTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FormularioLayout.createSequentialGroup()
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormularioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TXTNumE, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(TXTBalance)))
                    .addGroup(FormularioLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BTNRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormularioLayout.setVerticalGroup(
            FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormularioLayout.createSequentialGroup()
                .addComponent(BarraTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTNumE, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXTBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Balance))
                .addGap(26, 26, 26)
                .addComponent(BTNRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SombraLayout = new javax.swing.GroupLayout(Sombra);
        Sombra.setLayout(SombraLayout);
        SombraLayout.setHorizontalGroup(
            SombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Formulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SombraLayout.setVerticalGroup(
            SombraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SombraLayout.createSequentialGroup()
                .addComponent(Formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        Exit.setBackground(new java.awt.Color(27, 33, 65));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(Sombra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Sombra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(Exit)
                .addContainerGap())
        );

        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRegistrarActionPerformed
        RegistroEmpleados();
    }//GEN-LAST:event_BTNRegistrarActionPerformed

    private void BTNLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLeerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BTNLeerActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLeer;
    private javax.swing.JButton BTNRegistrar;
    private javax.swing.JLabel Balance;
    private javax.swing.JPanel BarraTop;
    private javax.swing.JButton Exit;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Formulario;
    private javax.swing.JPanel Sombra;
    private javax.swing.JTextField TXTBalance;
    private javax.swing.JTextField TXTNumE;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
